version: '3.8'

services:
  web-xulyanh:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: web-xulyanh-app
    ports:
      - "5000:5000"
    restart: unless-stopped
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_HTTP_PORTS=5000
